name: chiller_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_core: ^1.0.4
  js: ^0.6.2
  provider: ^4.3.3
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  geocoder: ^0.2.1
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.5
  carousel_slider: ^3.0.0
  paginate_firestore: ^0.3.1
  persistent_bottom_nav_bar: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
