name: chiller_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dots_indicator: ^1.2.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  js: ^0.6.2
  provider: ^4.3.3
  geolocator: ^6.1.14
  google_maps_flutter: ^1.1.1
  geocoder: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
