name: chiller_admin
description: Admin panel web app of the chiller app.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
  firebase: ^9.0.0
  firebase_storage: ^8.0.0
  ars_progress_dialog: ^0.1.2
  flutter_admin_scaffold: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
